package com.kevin.mapper;

import com.kevin.beans.PageQuery;
import com.kevin.model.SysAcl;
import com.kevin.model.SysAclExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int countByExample(SysAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int deleteByExample(SysAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int insert(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int insertSelective(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    List<SysAcl> selectByExample(SysAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    SysAcl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysAcl record, @Param("example") SysAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByExample(@Param("record") SysAcl record, @Param("example") SysAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByPrimaryKey(SysAcl record);
    /*
    * 新增查询函数
    * */
    int countByAclModuleId(@Param("aclModuleId") int aclModuleId);

    List<SysAcl> getPageByAclModuleId(@Param("aclModuleId") int aclModuleId, @Param("page") PageQuery page);

    int countByNameAndAclModuleId(@Param("aclModuleId") int aclModuleId,@Param("name") String name,@Param("id") Integer id);

    List<SysAcl> getAll();

    List<SysAcl> getByIdList(@Param("idList") List<Integer> idList);

    List<SysAcl> getByUrl(@Param("url") String url);
}