package com.kevin.mapper;

import com.kevin.model.SysAclModule;
import com.kevin.model.SysAclModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAclModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int countByExample(SysAclModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int deleteByExample(SysAclModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int insert(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int insertSelective(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    List<SysAclModule> selectByExample(SysAclModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    SysAclModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysAclModule record, @Param("example") SysAclModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByExample(@Param("record") SysAclModule record, @Param("example") SysAclModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_acl_module
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByPrimaryKey(SysAclModule record);
    /*
    * 新增函数
    * */
    int countByNameAndParentId(@Param("parentId") Integer parentId,@Param("name") String name,@Param("id") Integer id);

    List<SysAclModule> getChildAclModuleListByLevel(@Param("level") String level);

    void batchUpdateLevel(@Param("sysAclModules") List<SysAclModule> sysAclModules);

    List<SysAclModule> getAllAclModule();

    int countByParentId(@Param("aclModuleId") int aclModuleId);
}