package com.kevin.mapper;

import com.kevin.model.SysDept;
import com.kevin.model.SysDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     *
     * 1，使用@Param注解
     * 当以下面的方式进行写SQL语句时：
     *     @Select("select column from table where userid = #{userid} ")
     *     public int selectColumn(int userid);
     *
     * 当你使用了使用@Param注解来声明参数时，如果使用 #{} 或 ${} 的方式都可以。
     *
     *     @Select("select column from table where userid = ${userid} ")
     *     public int selectColumn(@Param("userid") int userid);
     *
     * 当你不使用@Param注解来声明参数时，必须使用使用 #{}方式。如果使用 ${} 的方式，会报错。
     *
     *     @Select("select column from table where userid = ${userid} ")
     *     public int selectColumn(@Param("userid") int userid);

     * 2，不使用@Param注解
     *
     * 不使用@Param注解时，参数只能有一个，并且是Javabean。在SQL语句里可以引用JavaBean的属性，而且只能引用JavaBean的属性。
     *
     *     // 这里id是user的属性
     *     @Select("SELECT * from Table where id = ${id}")
     *     Enchashment selectUserById(User user);
     */
    int countByExample(SysDeptExample example);

    int deleteByExample(SysDeptExample example);

    int deleteByPrimaryKey(@Param("id") Integer id);

    int insert(SysDept record);

    int insertSelective(SysDept record);

    List<SysDept> selectByExample(SysDeptExample example);

    SysDept selectByPrimaryKey(@Param("id") Integer id);

    int updateByExampleSelective(@Param("record") SysDept record, @Param("example") SysDeptExample example);

    int updateByExample(@Param("record") SysDept record, @Param("example") SysDeptExample example);

    int updateByPrimaryKeySelective(SysDept record);

    int updateByPrimaryKey(SysDept record);

    List<SysDept> getAllDept();

    List<SysDept> getChildDeptListByLevel(@Param("level") String level);

    void batchUpdateLevel(@Param("sysDeptList") List<SysDept> sysDeptList);

    int countByNameAndParentId(@Param("parentId") Integer parentId,@Param("name") String name,@Param("id") Integer id);
}