package com.kevin.mapper;

import com.kevin.model.SysRoleAcl;
import com.kevin.model.SysRoleAclExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface SysRoleAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int countByExample(SysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int deleteByExample(SysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int insert(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int insertSelective(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    List<SysRoleAcl> selectByExample(SysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    SysRoleAcl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleAcl record, @Param("example") SysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByExample(@Param("record") SysRoleAcl record, @Param("example") SysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbggenerated Tue Sep 11 11:19:45 CST 2018
     */
    int updateByPrimaryKey(SysRoleAcl record);
    /*
    * 新增函数
    * */
    List<Integer> getAclIdListByRoleIdList(@Param("roleIdList") List<Integer> roleIdList);

    void deleteByRoleId(@Param("roleId") int roleId);

    void batchInsert(@Param("roleAclList") List<SysRoleAcl> roleAclList);

    List<Integer> getRoleIdListByAclId(@Param("aclId") int aclId);

}